version: "3.9"

services:
  postgress-db:
    container_name: postgress-db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: vs_User
      POSTGRES_PASSWORD: vs_Password
      POSTGRES_DB: vs_database
    ports:
      - 5432:5432
    volumes:
      - ./postgresdat:/var/lib/postgresql/data
  nestjs:
    container_name: nestjs
    build:
      dockerfile: Dockerfile
      context: ./shopping-list-nest-backend
      # target: development
      target: production
    volumes:
      - ./shopping-list-nest-backend:/usr/src/app
      - /usr/src/app/node_modules
    # command: npm run dev
    # command: npm run debug
    command: npm run prod
    environment: 
      NODE_ENV: production
      # NODE_ENV: development
      PORT: 3000
      DB_PORT: 5432
      DB_HOST: postgress-db
      DB_USER: vs_User
      DB_PASS: vs_Password
      POSTGRES_DB: vs_database
    ports:
      - 3000:3000
    depends_on:
        - postgress-db
    links: 
        - postgress-db
